# Generated by Django 4.1.7 on 2023-04-06 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0004_alter_stock_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='products',
            new_name='positions',
        ),
        migrations.AlterField(
            model_name='stockproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistic.product'),
        ),
        migrations.AlterField(
            model_name='stockproduct',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistic.stock'),
        ),
    ]
